### PR TITLE
Minimal migration to use OWENSOpenFAST_jll

### PR DESCRIPTION
**Pull request by fredrikekre**
This patch make use of BinaryBuilder.jl precompiled binaries via the OWENSOpenFAST_jll package. For me (on x86-64-linux-gnu) tests pass for this package locally.

Note that once openfast version 4 is released, the existing build recipe in Yggdrasil can be updated and then we migrate to use the existing package hosted at https://github.com/JuliaBinaryWrappers/OpenFAST_jll.jl instead. The reason for this is that neigher Yggdrasil/BinaryBuilder nor Pkg supports pre-releases properly.

### CODE REVIEW

**Comment by kevmoor** [comment]
It looks like the failures for 1.6 and docs are just from it not picking up the package location, which shouldn't be an issue once it's registered.  If there is anything else you think should be done for this, please update, otherwise I'll merge this in.

**Comment by fredrikekre** [comment]
I can fix the CI to pick it up first

**Comment by kevmoor** [comment]
Transfer was successful for the jll repo to my account

**Comment by kevmoor** [comment]
Scratch that, I got it into sandialabs

**Pull request merged**
